research_sample = [
    "What is the main research question addressed in this paper?",
    "Can you summarize the abstract in simple terms?",
    "What methodology did the authors use?",
    "What are the key contributions of this paper?",
    "How does this work compare to previous research?",
    "What are the limitations mentioned by the authors?",
    "Can you explain the proposed model step by step?",
    "What evaluation metrics were used, and why?",
    "Are the experimental results statistically significant?",
    "Can you explain Figure 3 and its findings?",
    "What assumptions does this research make?",
    "What datasets were used in the experiments?",
    "Can you explain the mathematical formulation in Section 4?",
    "What future work do the authors suggest?",
    "How could this method be applied in practice?",
    "What are the strengths and weaknesses of this paper?",
    "Can you explain the loss function used in this model?",
    "Why did the authors choose this baseline for comparison?",
    "What are the most important takeaways from this paper?",
    "Can you help me understand this paragraph from the paper?"
]

chitchat = [
    "Hi, how are you today?",
    "What's your favorite movie genre?",
    "Tell me something interesting.",
    "How's your day going?",
    "What's the weather like today?",
    "Do you like coffee or tea?",
    "What's a fun fact about space?",
    "Can you recommend a good book?",
    "What music do you enjoy?",
    "Tell me a joke.",
    "If you could travel anywhere, where would you go?",
    "What's your favorite season?",
    "What should I cook for dinner tonight?",
    "How can I stay productive while working from home?",
    "What's a good hobby to pick up?",
    "Do you play any games?",
    "What's the best way to relax after a busy day?",
    "Can you recommend a good TV series?",
    "What's something new I should learn this month?",
    "Good night! Hope tomorrow is a great day."
]